version: '3'
services:
  vault:
    image: vault:1.0.2
    ports: [8200]
    networks: [internal]
    environment:
      VAULT_API_ADDR: http://127.0.0.1:8200
      VAULT_LOCAL_CONFIG: >-
        {
          "disable_mlock": 1,
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address":     "0.0.0.0:8200",
              "tls_disable": 1
            },
          },
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h"
        }
    cap_add:
      - IPC_LOCK
    volumes:
      - 'vault-data:/vault/file'
    command: 
      - vault
      - server
      - "-config"
      - "/vault/config/local.json"

  core:
    depends_on:
      - vault
    image: 'shieldproject/shield:8'
    ports: ['9009:80']
    networks: [internal]
    command: ['/shield/init/core', '--log-level', 'debug']
    environment:
      VAULT_ADDR: http://vault:8200
      DEBUG:      'yes'

      SHIELD_ENV_NAME: documentum
      SHIELD_COLOR:    lightgreen
    volumes:
      - 'shield-data:/var/shield'
      - 'shield-etc:/etc/shield'

  agent:
    depends_on:
      - core
      - webdav
    image: 'shieldproject/shield:8'
    ports: [5444]
    networks: [internal]
    command: ['/shield/init/agent', '--log-level', 'debug']
    environment:
      SHIELD_API: 'http://core:80'
      DEBUG:      'yes'
    volumes:
      - 'shield-data:/var/shield'
      - 'shield-etc:/etc/shield'
      - 'shield-test:/data'

  webdav:
    image: 'morrisjobke/webdav:latest'
    ports: [80]
    networks: [internal]
    environment:
      USERNAME: webdav
      PASSWORD: password
    volumes:
      - 'webdav-data:/var/webdav'

networks:
  internal:

volumes:
  vault-data:
  shield-data:
  shield-etc:
  webdav-data:
  shield-test:
